### ISSUE TITLE
Error when loading progress bar as python module and using custom message function

### ISSUE THREAD

**Issue by LoganAC34** [Cyril-Pop/Dynamo_PythonProgressBar#3]
I found a bug regarding [my issue](https://github.com/Cyril-Pop/Dynamo_PythonProgressBar/issues/1) from a little while ago.

Using the loading method from [this post](https://voltadynabim.blogspot.com/2021/04/dynamopython-un-exemple-de-barre-de.html#:~:text=soit%20en%20important%20le%20fichier%20script%20Python%20%22ProgressBarUtils.py%22%20comme%20module%20(IronPython%20ou%20CPython/Pythonnet)) and this code:
```
import sys
import clr
import System

from System.IO import Path
file_PathPy = IN[0]
folderPy = Path.GetDirectoryName(file_PathPy)
sys.path.append(folderPy)
import ProgressBarUtils
from ProgressBarUtils import ProgressBarUtils as pgb
```

I get the error of:
```
Warning: TypeError : myFunction() takes 1 positional argument but 2 were given ['  File "<string>", line 92, in <module>\n', '  File "<location to file>\ProgressBarUtils.py", line 115, in next_p\n    class EventHook():\n']
```

This error has to do with this line in my code:
`broadcaster.onChange.next_p(msg)`

If I remove the msg variable, I get no error and code runs like normal. 
If I load the progress bar code by assigning the Class to the OUT variable, everything run like it should with the custom message, but I would like everything to be contained in one python node.

**Comment by Cyril-Pop** [comment]
Hello,
I can't reproduce the error, can you share your dyn and py file ?

**Comment by LoganAC34** [comment]
I can't reproduce it now either, Its working now. I've been working on my code for a while now and changed a lot. Not sure what I changed to fix it or if it was just a fluke. Sorry for the bother. I'll let you know if it happens again. Thanks for looking into it.
